#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    exit(1);
}

ini_set('memory_limit', '256M');
gc_enable();

require_once __DIR__ . '/../config/config.php';

use League\CLImate\CLImate;
use Sintoniza\Cli\UpdateFeeds;
use Sintoniza\Library\Container;
use Sintoniza\Service\FeedService;

$container = Container::getInstance();
$climate   = new CLImate();

$args    = array_slice($argv, 1);
$command = 'update';

if (!empty($args) && !str_starts_with($args[0], '--')) {
    $command = array_shift($args);
}

$maxFeeds = null;

foreach ($args as $arg) {
    if (preg_match('/^--max-feeds=(\d+)$/', $arg, $m)) {
        $maxFeeds = (int) $m[1];
    } elseif (preg_match('/^--limit=(\d+)$/', $arg, $m)) {
        $maxFeeds = (int) $m[1];
    }
}

$feedService = $container->get(FeedService::class);

match ($command) {
    'update' => (new UpdateFeeds($feedService, $climate))->run($maxFeeds),
    default => (function () use ($climate, $command) {
        $climate->red()->bold(sprintf('Unknown command: %s', $command));
        $climate->out('Available commands:');
        $climate->out('  update            Update stale feeds (respect next_fetch_at)');
        $climate->out('');
        $climate->out('Options:');
        $climate->out('  --max-feeds=N  | --limit=N    Maximum number of feeds to process');
        exit(2);
    })(),
};
