services:
  sintoniza:
    container_name: sintoniza
    image: ghcr.io/manualdousuario/sintoniza:latest
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: database_user
      DB_PASS: database_password
      DB_NAME: database_name
      BASE_URL: https://sintoniza.xyz/
      TITLE: Sintoniza
      ADMIN_PASSWORD: p@ssw0rd
      DEBUG: true
      ENABLE_SUBSCRIPTIONS: true
      DISABLE_USER_METADATA_UPDATE: false
      SMTP_USER: email@email.com
      SMTP_PASS: password
      SMTP_HOST: smtp.email.com
      SMTP_FROM: email@email.com
      SMTP_NAME: "Sintoniza"
      SMTP_PORT: 587
      SMTP_SECURE: tls
      SMTP_AUTH: true
    depends_on:
      - db
  db:
    image: mariadb:10.11
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: database_password
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
