name: GitHub Docker Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Get version from config.php
        id: get-version
        run: |
          VERSION=$(grep -Po '(?<=define\("VERSION",\s*")[^"]*' src/config.php)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: all

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sintoniza:latest
            ghcr.io/${{ github.repository }}/sintoniza:${{ steps.get-version.outputs.version }}

      - name: Verify Docker image
        run: docker images
